---

- hosts: all
  tasks:
  
  - name: udpate ubuntu
    apt:
     update_cache: true

  - name: install docker 
    apt: 
     name: docker
     state: latest

  - name: docker start
    systemd:
     name: docker
     state: started
     enabled: true

