---
- hosts: all
  tasks:
    - name: update the package
      apt:
        update_cache: true
      
    - name: install apache2 package
      apt:
        name: apache2
        state: latest
      
    - name: install php
      apt:
        name: libapache2-mod-php
        state: latest     
