---
- hosts: all
  become: yes
  
  vars:
   node_apps_location: /usr/local/opt/node
 
  tasks:
   - name: Install EPEL repo.
     apt: name=epel-release state=present
     
   - name: Import Remi GPG key.
     rpm_key:
       key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
       state: present
       
   - name: Install Remi repo.
     apt:
      name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
      state: present
      
   - name: Ensure firewalld is stopped (since this is for testing).
     service: name=firewalld state=stopped
     
   - name: Install Node.js and npm.
     apt: name=npm state=present enablerepo=epel

   - name: Install Forever (to run our Node.js app).
     apt: name=forever global=yes state=present
     
   - name: Ensure Node.js app folder exists.
     file: "path={{ node_apps_location }} state=directory"
     
   - name: Copy example Node.js app to server.
     copy: "src=app dest={{ node_apps_location }}"

   - name: Install app dependencies defined in package.json.
     npm: path={{ node_apps_location }}/app
